### ISSUE TITLE
Error when importing solid-js and solid-js/web

### ISSUE THREAD

**Issue by modderme123** [lukasbach/monaco-editor-auto-typings#2]
This project looks super cool! I was looking at incorporating it into https://playground.solidjs.com, and was running into issues when importing `solid-js` and `solid-js/web` together. For example, try these two imports on the demo: 
```ts
import { render } from "solid-js/web";
import { createSignal } from "solid-js";
```

Maybe this is because the importer isn't finding the second package.json file at `solid-js/web`, or is parsing `solid-js/web` as `solid-js` but adding it a second time?
```ts
Error: ModelService: Cannot add model because it already exists!
    at ModelServiceImpl2._createModelData
```

If you have any advice about how to work around this (such as disabling imports for the solid-js package and manually adding those in myself), I would love to hear them.

**Comment by lukasbach** [comment]
Hi @modderme123!

Hm, interesting problem. From what I can tell after quick inspection, I do think the issue comes from `solid-js` having two different package.json files as you've said, however `monaco-editor-auto-typings` always emulates the existence of one top-level package.json file for every package (https://github.com/lukasbach/monaco-editor-auto-typings/blob/master/packages/core/src/ImportResolver.ts#L107).

Maybe its possible to take the original path of the package.json file into consideration. If you want, you can take a PR on this, otherwise I'll see if I find time to solve it.

I can't really think of any easy workarounds. I guess the types you are trying to get from `solid-js/web` are not exported from `solid-js` at all, right?

**Comment by lukasbach** [comment]
@modderme123 

Because it seemed like a solution was not as trivial as I've expected, I've went ahead and implemented a solution myself. `monaco-editor-auto-typings` should now be able to support packages with nested package.json files as of version 0.0.5, which I've just released. Can you try out the [project playground](https://lukasbach.github.io/monaco-editor-auto-typings/) to see if your code produces the expected typings? You might need to clear the declaration cache or your browser cache for it to work. Thanks :)

**Comment by modderme123** [comment]
I setup a local test and it worked! Thanks for figuring this out!

**Comment by lukasbach** [comment]
Great, happy to hear! 👍
