### ISSUE TITLE
[REQUEST] cannot work with monaco-editor@0.25.0

### ISSUE THREAD

**Issue by maslow** [lukasbach/monaco-editor-auto-typings#3]
no errors ocurred, but no packages typed, i have spent lots of time on it .

**Comment by lukasbach** [comment]
Hi @Maslow!

I found that there were in fact incompatibilities with newer versions of monaco-editor, that should now be fixed with the latest version of `monaco-editor-auto-typings` (v0.1.0). Can you check whether you still experience issues with the new version? If not, can you provide more details on the context of your project?

**Comment by futhr** [comment]
Current version is `monaco-editor@0.31.1` and this package use `monaco-editor@0.26.1`, no errors but no typings injected.
